import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Header'

export const metadata: Metadata = {
  title: 'Kevin News App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <script src="https://test.hitmeup.ai/widget.js/?rec=56&token=381259e4-3ca0-4c56-9948-3135423feb1b%27" async></script>
      <body className="bg-white dark:bg-zinc-900 dark:text-white transition-all duration-700">
        <Header />
        <div className="max-w-6xl mx-auto">
            {children}
        </div>
      </body>
    </html>
  )
}
