import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Header'

export const metadata: Metadata = {
  title: 'Kevin News App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <script src="https://intent-anchovy-main.ngrok-free.app/widget.js/?rec=1&token=f56e3fc1-d943-4559-9731-10e0f186a1e6" async></script>
      </head>
      <body className="bg-white dark:bg-zinc-900 dark:text-white transition-all duration-700">
        <Header />
        <div className="max-w-6xl mx-auto">
            {children}
        </div>
      </body>
    </html>
  )
}
